### ISSUE TITLE
Link Hints on YouTube

### ISSUE THREAD

**Issue by de-Blaxe** [de-Blaxe/sVim#1]
Link Hints on YouTube don't seem to display properly. It's as if the style sheet hasn't been loaded.

**Comment by chlumpchatkupt** [comment]
I cannot replicate this. Hints work fine for me on YouTube.

Have you tried adding '!important' to the various lines in the css file?

What happens if you try to follow a link?

**Comment by de-Blaxe** [comment]
Thank you for the suggestion! That seems to have fixed it.
